config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  devise_for :users
  resources :events

  resources :subscribers do
      resources :homes
  end

  root 'home#index'

  get '/eventos' => 'events#index'
  get '/eventos/:id' => 'events#show'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  before_save :number_views
  validates :photo, presence: true
  validates :cover, presence: true

  has_attached_file :cover, styles: { :medium => "900x600#" }
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  has_attached_file :photo, styles: { :medium => "300x200#" }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def update_view_count
    self.update(view_count: self.view_count + 1)
  end



  private

  def number_views
    self.view_count ||= 0
  end

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event.update_view_count
    @tags = @event.tags.split(",")
    @from_time = Time.now
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @user = current_user
    @event = @user.events.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @user = current_user
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :body, :start, :view_count, :tags, :user_id, :photo, :cover, :lugar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subscriber = Subscriber.new
    @events = Event.all
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to root_path, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:nombres, :apellidos, :correo, :preferencias)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

  def form_image_select(event)
    return image_tag event.cover.url,
                     id: 'image-preview',
                     class: 'responsive-img' if event.cover.exists?
    image_tag 'placeholder.png', id: 'image-preview', class: 'responsive-img'
  end

  def form_logo_select(event)
    return image_tag event.photo.url,
                     id: 'photo-preview',
                     class: 'responsive-img' if event.photo.exists?
    image_tag 'placeholder.png', id: 'photo-preview', class: 'responsive-img'
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribernombres_helper.rb
module SubscribernombresHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/events/_form.html.haml
= simple_form_for @event, html: { multipart: true } do |f|
  - if event.errors.any?
    #error_explanation
      %h2
        = pluralize(event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - event.errors.full_messages.each do |message|
          %li= message
  .form-content
    .form-wrap
      .field-image
        .load-images
          .images
            #upload-img
              .file.fileUpload
                = f.file_field :cover , label: false, onChange: 'previewFile()'
              %button Seleccionar Portada
          = form_image_select(@event)

        .load-images
          .images
            #upload-img
              .file.fileUpload
                = f.file_field :photo , label: false, onChange: 'previewFile2()'
              %button Seleccionar Logo
          = form_logo_select(@event)

      .field-form
        = f.input :title , label: false, placeholder: "Nombre del Evento", class: "inputs"
      .field-form
        = f.input :lugar , label: false, placeholder: "Lugar", class: "inputs"
      .field-form
        = f.input :start, as: :datetime, label: false
      .field-form
        ~ f.cktext_area  :body, as: :text, label: false, placeholder: "Descripcion del Evento"
      .field-form
        = f.text_field :tags ,id: "inputTag", :data => {:role => "materialtags"} , placeholder: "Ejemplo: Emprendimiento, Innovacion,etc"
      .btn-guardar
        = f.button :submit ,"Guardar Evento"

app/views/events/edit.html.haml
%h1 Editing Event
= render 'form', event: @event
= link_to 'Show', @event
|
= link_to 'Back', eventos_path

app/views/events/index.html.haml
%p#notice= notice
.eventos
  .eventos-wrap
    - @events.each do |event|
      .event-list
        = link_to event, :action => 'show', class: "event-item"  do
          .logo-event= image_tag event.photo.url(:medium)
          .fecha-evento
            = event.start.day
            %br
            = l(event.start , format: :more_short_month)
          .body-evento
            %h2= event.title
          .date-info
            .lugar-event
              %p.icons-date ☉
              %p= event.lugar
            .hora-event
              %p.icons-date ⌛
              %p= l(event.start , format: :short_hour)

        .btn_admin
          = link_to '✍', edit_event_path(event)
          = link_to '✕', event, method: :delete, data: { confirm: 'Seguro que quieres eliminar este evento?' }
%br/
= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New Event
= render 'form', event: @event
= link_to 'Back', eventos_path

app/views/events/show.html.haml
%p#notice= notice
%section.cover{"data-stellar-background-ratio" => "0.5", :style => "background-image: url('#{@event.cover.url(:medium)}');"}
  .overlay-header
  %h2.titulo
    = @event.title
  .fecha
  .status
    .views
      %i ♥
      %font= @event.view_count
    .likes
      %i ☺
      %font= @event.view_count
%section.contenido
  .contenido-wrap
    .info
      %font
        Publicado hace : #{time_ago_in_words(@event.created_at)}
      %font
        Por: #{@user.email}
    .line
    .body-event-main
      = raw @event.body
    .tags
      - @tags.each do |tag|
        %p= tag
= link_to 'Edit', edit_event_path(@event)
|
= link_to 'Back', events_path
= javascript_tag do
  $(".fecha").countdown({
  until: new Date(#{@event.start.year}, #{@event.start.month}-1, #{@event.start.day}, #{@event.start.hour},  #{@event.start.min})});

app/views/home/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "width=device-width", :name => "viewport"}/
    / Custom CSS
    %link{:href => "https://fonts.googleapis.com/css?family=Antic|Anton|Roboto+Condensed", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Lobster+Two", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Inconsolata", :rel => "stylesheet"}/
  %body


    .modal
      .modal-wrap
        .sus-form
          .sus-close
            %i.icon.icon-cancel
          .form-content
            .fields
              = render 'subscribers/form'
              .info-modal Suscribete para recibir información acerca de nuestros eventos y publicaciones.
              .social-modal
                %i
                  %a.icon.icon-facebook{:href => "https://www.facebook.com/Direcci%C3%B3n-de-Transferencia-e-Innovaci%C3%B3n-Unheval-881641215272116/", :target => "_blank"}
                %i
                  %a.icon.icon-twitter{:href => "https://twitter.com/DTI_Unheval", :target => "_blank"}
                %i
                  %a.icon.icon-youtube{:href => "https://www.youtube.com/channel/UCBbNSHmCDwwRkgty0H3wZcg", :target => "_blank"}


    %header#header
      %video{:autoplay => "autoplay", :loop => "loop", :muted => "muted", :poster => "/assets/portada.jpg", :src => "/assets/bg.mp4"}
      .overlay
      %nav
        .logo
          %img{:src => "/assets/logo.png"}/
        .items
          .toggle
            %i.icon.icon-menu3
          .close
            %i.icon.icon-close
          .tabs
            %li
              %a.hide.item{:href => "#about"} acerca de
            %li
              %a.hide.item{:href => "#eventos"} eventos
            %li
              %a.hide.item{:href => "#pub"} publicaciones
            %li
              %a.hide.item{:href => "#equipo"} equipo
            %li
              %a.hide.item{:href => "#"} contacto
          .suscribete.item.hide SUSCRIBETE
      .main-title DIRECCIÓN DE TRANSFERENCIA E INNOVACIÓN
      .span
        %img.scroll{:src => "/assets/scroll-icon.png", :width => "60"}/
    %section#about.about-section{"data-stellar-background-ratio" => "0.5", "data-stellar-vertical-offset" => "0"}
      .overlay-about
      .about-container
        .about-wrap.show
          .about-content
            %h2.mision NUESTRA VISION
            %p.mision La Dirección de Transferencia e Innovación (DTI) es un órgano dependiente del Vicerrectorado de Investigación, encargada de promover y gestionar relaciones e interacciones entre la UNHEVAL y su entorno, particularmente, el sector empresarial, en el área de la investigación e innovación tecnológica. Específicamente está encargada de transferir los resultados de los trabajos de investigación y prestaciones de servicios con entidades públicas y privadas; organizar información para empresas; publicaciones; proteger la propiedad intelectual y el registro de patentes.
        .about-wrap
          .about-content
            %h2.vision NUESTRA MISION
            %p.vision La Dirección de Transferencia e Innovación (DTI) es un órgano dependiente del Vicerrectorado de Investigación, encargada de promover y gestionar relaciones e interacciones entre la UNHEVAL y su entorno, particularmente, el sector empresarial, en el área de la investigación e innovación tecnológica. Específicamente está encargada de transferir los resultados de los trabajos de investigación y prestaciones de servicios con entidades públicas y privadas; organizar información para empresas; publicaciones; proteger la propiedad intelectual y el registro de patentes.
        .about-wrap
          .about-content
            %h2.valores NUESTROS VALORES
            %p.valores La Dirección de Transferencia e Innovación (DTI) es un órgano dependiente del Vicerrectorado de Investigación, encargada de promover y gestionar relaciones e interacciones entre la UNHEVAL y su entorno, particularmente, el sector empresarial, en el área de la investigación e innovación tecnológica. Específicamente está encargada de transferir los resultados de los trabajos de investigación y prestaciones de servicios con entidades públicas y privadas; organizar información para empresas; publicaciones; proteger la propiedad intelectual y el registro de patentes.
        .about-wrap
          .about-content
            %h2.proposito NUESTRO PROPOSITO
            %p.proposito La Dirección de Transferencia e Innovación (DTI) es un órgano dependiente del Vicerrectorado de Investigación, encargada de promover y gestionar relaciones e interacciones entre la UNHEVAL y su entorno, particularmente, el sector empresarial, en el área de la investigación e innovación tecnológica. Específicamente está encargada de transferir los resultados de los trabajos de investigación y prestaciones de servicios con entidades públicas y privadas; organizar información para empresas; publicaciones; proteger la propiedad intelectual y el registro de patentes.
    .wrap-slide
      %span
        .msg-btn
          .shape.show
            .bubble.bubble-mision vision
            .tip
          .slide-button
        .msg-btn
          .shape
            .bubble.bubble-vision mision
            .tip
          .slide-button
        .msg-btn
          .shape
            .bubble.bubble-valores valores
            .tip
          .slide-button
        .msg-btn
          .shape
            .bubble.bubble-proposito proposito
            .tip
          .slide-button
    %section#areas.areas-section
      .area.a1
        .hover-area
        %i
        %p Oferta Tecnológica
        %br/
        %span conócenos
      .area.a2
        .hover-area
        %i
        %p Propiedad Intelectual, Patentes  y Publicaciones
        %span conócenos
      .area.a3
        .hover-area
        %i
        %p Emprendimiento e Incubadora  de Empresas
        %span conócenos
    %section#eventos.eventos-section
      .overlay-evento
      .title-eventos
        %h2 Nuestros Eventos
      .eventos-wrap
        - @events.each do |event|
          .evento-content
            = link_to event, :action => 'show', class: "event-item"  do
              .date
                = event.start.day
                = l(event.start , format: :more_short_month)
              = image_tag event.photo.url(:medium), :width => "250"
              %p= event.title
      .btn_event
        = link_to "Ver Todas", eventos_path
    %section#numeros.numeros-section{"data-stellar-background-ratio" => "0.5"}
      .overlay-numeros
      .dark-bg
      .numeros-wrap
        .numero
          %i.icon.icon-happy
          %h2
            %span.count 50
          %p Convenios
        .numero
          %i.icon.icon-presentation
          %h2
            %span.count 40
          %p Proyectos
        .numero
          %i.icon.icon-flag
          %h2
            %span.count 20
          %p Objetivos Logrados
        .numero
          %i.icon.icon-hourglass
          %h2
            %span.count 30
          %p Años de Experiencia
    %section#pub.pub-section
      .overlay-pub
      .title-pub
        %h2 Publicaciones
      .pub-container
        .move-right
          %span.icon.icon-arrow-left
        .pub-wrap
          .pub-move
            .pub-content
              %img{:src => "/assets/pub_img1.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 1
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
            .pub-content
              %img{:src => "/assets/pub_img2.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 2
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
            .pub-content
              %img{:src => "/assets/pub_img3.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 3
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
            .pub-content
              %img{:src => "/assets/pub_img1.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 4
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
            .pub-content
              %img{:src => "/assets/pub_img2.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 5
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
            .pub-content
              %img{:src => "/assets/pub_img3.jpg", :width => "100%"}/
              .pub-body
                .pub-title Publicacion 6
                .pub-text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui nam minus aliquid quia, quaerat quisquam, officia eveniet fugiat vero praesentium tempora numquam accusantium quos sint perferendis, odit cupiditate possimus nobis.
        .move-left
          %span.icon.icon-arrow-right
      .btn_pub
        %span ver todas
    %section#equipo.equipo-section
      .equipo-wrap
        %h2 CONOCE A NUESTRO EQUIPO
        .miembros
          .miembro
            .img-profile
              %img{:src => "/assets/profile1.jpg"}/
              .semi-circulo.color1
            %b Nerida del Carmen Pastrana Diaz
            %span Directora DTI
          .miembro
            .img-profile
              %img{:src => "/assets/profile2.jpg"}/
              .semi-circulo.color2
            %b Amparo Espinoza Chávez
            %span Jefa DTI
          .miembro
            .img-profile
              %img{:src => "/assets/profile3.jpg"}/
              .semi-circulo.color3
            %b Carlos Manuel Ventura Matos
            %span Coordinador EIE
          .miembro
            .img-profile
              %img{:src => "/assets/profile4.jpg"}/
              .semi-circulo.color4
            %b Brittzzi Zarate Casachahua
            %span Coordinadora PIPP
          .miembro
            .img-profile
              %img{:src => "/assets/profile5.jpg"}/
              .semi-circulo.color5
            %b Yeltsin Josue Minaya Mallqui
            %span Editor  de Contenido e Imagen
          .miembro
            .img-profile
              %img{:src => "/assets/profile1.jpg"}/
              .semi-circulo.color6
            %b Sin Nombre
            %span Coordinador OT
    %section.socios-section
      .socios-wrap
        %img{:src => "/assets/socio1.png"}/
        %img{:src => "/assets/socio2.png"}/
        %img{:src => "/assets/socio3.png"}/
    %section.footer-section{"data-stellar-background-ratio" => "0.5", "data-stellar-vertical-offset" => "0"}
      .dark-footer
      .overlay-footer
      .footer-wrap
        .contact
          .social-icon
            %i
              %a.icon.icon-facebook{:href => "https://www.facebook.com/Direcci%C3%B3n-de-Transferencia-e-Innovaci%C3%B3n-Unheval-881641215272116/", :target => "_blank"}
            %i
              %a.icon.icon-twitter{:href => "https://twitter.com/DTI_Unheval", :target => "_blank"}
            %i
              %a.icon.icon-youtube{:href => "https://www.youtube.com/channel/UCBbNSHmCDwwRkgty0H3wZcg", :target => "_blank"}
          .phone
            %b> Teléfono:
            (062) - 591060
          .mail
            %b> Correo:
            dti.vri@unheval.edu.pe
        .question
          %p ¿Alguna Consulta?
          .form-consulta
            %input.field-q{:placeholder => "Email", :type => "text"}/
            %input.field-q{:placeholder => "Asunto", :type => "text"}/
            %textarea.consulta{:placeholder => "Mensaje"}
            %input.btn-q{:type => "submit", :value => "Enviar"}/
        .other
          .logo-unheval
            %img{:src => "/assets/logo-unheval.png"}/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DtiWeb
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Dosis:200|Open+Sans:700|Roboto:300", :rel => "stylesheet"}/
  %body
    ~ yield

app/views/subscribers/_form.html.haml
= form_for @subscriber do |f|
  - if @subscriber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscriber.errors.count, "error")} prohibited this subscriber from being saved:"
      %ul
        - @subscriber.errors.full_messages.each do |msg|
          %li= msg

  .fields
    = f.label :nombres
    = f.text_field :nombres , class: "field-sub"
    = f.label :apellidos
    = f.text_field :apellidos , class: "field-sub"
    = f.label :correo
    = f.text_field :correo , class: "field-sub"
    = f.label :preferencias
    = f.text_field :preferencias , class: "field-sub", placeholder: "Ejemplo: Emprendimiento,Innovacion,etc"
  .actions
    = f.submit 'Suscribirse', class: "sus-btn"

app/views/subscribers/edit.html.haml
%h1 Editing subscriber

= render 'form'

= link_to 'Show', @subscriber
\|
= link_to 'Back', subscribers_path

app/views/subscribers/index.html.haml
%h1 Listing subscribers

%table
  %thead
    %tr
      %th Nombres
      %th Apellidos
      %th Correo
      %th Preferencias
      %th
      %th
      %th

  %tbody
    - @subscribers.each do |subscriber|
      %tr
        %td= subscriber.nombres
        %td= subscriber.apellidos
        %td= subscriber.correo
        %td= subscriber.preferencias
        %td= link_to 'Show', subscriber
        %td= link_to 'Edit', edit_subscriber_path(subscriber)
        %td= link_to 'Destroy', subscriber, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subscriber', new_subscriber_path

app/views/subscribers/new.html.haml
%h1 New subscriber

= render 'form'

= link_to 'Back', subscribers_path

app/views/subscribers/show.html.haml
%p#notice= notice

%p
  %b Nombres:
  = @subscriber.nombres
%p
  %b Apellidos:
  = @subscriber.apellidos
%p
  %b Correo:
  = @subscriber.correo
%p
  %b Preferencias:
  = @subscriber.preferencias

= link_to 'Edit', edit_subscriber_path(@subscriber)
\|
= link_to 'Back', subscribers_path